apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    {{- if or .Values.db.enabled .Values.kafka.enabled }}
    spring:
      {{- if .Values.db.enabled }}
      datasource:
        url: jdbc:postgresql://{{ .Values.db.host }}:5432/{{ .Values.db.name }}
      {{- end }}
      {{- if .Values.kafka.enabled }}
      kafka:
        bootstrap-servers: {{ .Values.kafka.bootstrapServers }}
      {{- end }}
    {{- end }}