apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: gcp
  parameters:
    secrets: |
      {{- if .Values.db.enabled }}
      - resourceName: "projects/{{ .Values.global.gcpProjectId }}/secrets/{{ .Values.appName }}-db-username/versions/latest"
        path: "db-username"
      - resourceName: "projects/{{ .Values.global.gcpProjectId }}/secrets/{{ .Values.appName }}-db-password/versions/latest"
        path: "db-password"
      {{- end }}
      {{- if .Values.jwt.privateKey.enabled }}
      - resourceName: "projects/{{ .Values.global.gcpProjectId }}/secrets/{{ .Values.appName }}-jwt-private-key/versions/latest"
        path: "jwt-private-key"
      {{- end }}
      {{- if .Values.jwt.publicKey.enabled }}
      - resourceName: "projects/{{ .Values.global.gcpProjectId }}/secrets/{{ .Values.appName }}-jwt-public-key/versions/latest"
        path: "jwt-public-key"
      {{- end }}
  secretObjects:
    {{- if .Values.db.enabled }}
    - secretName: {{ .Values.db.credentialsSecretName }}
      type: kubernetes.io/basic-auth
      data:
        - objectName: db-username
          key: username
        - objectName: db-password
          key: password
    {{- end }}
    {{- if .Values.jwt.privateKey.enabled }}
    - secretName: {{ .Values.jwt.privateKey.secretName }}
      type: Opaque
      data:
        - objectName: jwt-private-key
          key: private-key
    {{- end }}
    {{- if .Values.jwt.publicKey.enabled }}
    - secretName: {{ .Values.jwt.publicKey.secretName }}
      type: Opaque
      data:
        - objectName: jwt-public-key
          key: public-key
    {{- end }}