apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.appName }}-gsm-reader@{{ .Values.global.gcpProjectId }}.iam.gserviceaccount.com"
